#!/bin/bash
device=$1
temp=$2
rain=$3
humidity=$4
bat=$5
raw=$6
name=$7

DATE=`date "+%Y-%m-%d"`
TIME=`date "+%H:%M:%S"`
FILENAME=/home/pi/log/$DATE"_data.txt"
# cpt;date;time;temp;press;humi;temp2;bat;rain;raw;name;
echo "$device;$DATE;$TIME;$temp;0;$humidity;0.0;$bat;$rain;$raw;$name" >>  $FILENAME
